#!/usr/bin/env bash
set -o nounset;
set -o errexit;
set -o pipefail;

IFS=$'\n\t'

NAME="${1}.schema"
SCHEMA="${NAME}.json"
if [[ ! -f "${SCHEMA}" ]]; then
  >&2 echo ":: missing schema file '${SCHEMA}'"
  exit 1
fi

source .access
curl --verbose \
  -XPOST \
  --header 'Content-Type: application/json' \
  --silent \
  --show-error \
  --user "${SUMOLOGIC_ACCESS_ID}:${SUMOLOGIC_ACCESS_KEY}" \
  --data "@${SCHEMA}" \
  --output "create_table.${NAME}.$(date +'%s').log" \
  'https://api.us2.sumologic.com/api/v1/lookupTables'

#https://api.sumologic.com/docs/#operation/createTable
